version: '3'

services: 
  mysql: 
    image: mysql 
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin 
    environment: 
      PMA_ARBITRARY: 1 
      PMA_HOST: mysql 
      PMA_USER: root 
      PMA_PASSWORD: password 
    restart: always 
    links: 
      - mysql:mysql 
    ports : 
      - 8080:80 
    volumes: 
      - mysql-data:/lib/mysql

volumes: 
  mysql-data: 
    driver: local
